@startuml
class ListManagement {


    -String titleS
    -ArrayList titleAL
    -String dateS
    -ArrayList dateAL
    -String descriptionS
    -ArrayList descriptionAL
    -bool completionCheckB
    -ArrayList completionCheckAL

    +ArrayList nameFinal
    +ArrayList countFinal

    +getTitle
    +setTitle()

    +getDescription()
    +setDescription()

    +getCompletionCheck()
    +setCompletionCheck()

    +addToList()
    -sortList()
    +removeToList()
    +printCompleteList()
    +printIncompleteList()
}

class ListMoveOperations {


    +String readFile
    +ArrayList tempHolder1
    +ArrayList tempHolder2
    +ArrayList tempHolder3

    +readFromFile()
    +writeFromFile()
}

class Interface {

    main()
    start()

    newList()
    addtoList()
    remfromList()
    sendtoText()
    listfromText()

    +FileManagement Object
  +everything activated using the FM Object
}



javafx.Application <|-- Interface
Interface - ListManagement
Interface - ListMoveOperations
@enduml